name: Market
main: com.chromaclypse.market.MarketMain
version: ${project.version}
description: Virtual trade via shifting prices
author: ezeiger92
api-version: 1.13
depend: [ChromaLib, ChestShop]
commands:
  market:
    description: Root Market command
    usage: /<command> [args ...]
    permission: market.create
permissions:
  market.create:
    description: Create markets
    default: op
